#ifndef _STRING_RESOURCE_H_ 
 #define _STRING_RESOURCE_H_  
 

typedef enum  {               
MAIN_MENU,    //   MAIN MENU
CHECK_LOCAL_STOCK,    //  1 CHECK LOCAL STOCK
CHECK_REMOTE_STOCK,    //  2 CHECK REMOTE STOCK
PRINT_PIN,    //  3 PRINT PIN
DOWNLOAD_PIN,    //  4 DOWNLOAD PIN
REPORT_SALE,    //  5 REPORT SALES
RETURN_STOCK,    //  6 RETURN STOCK
XAF500,    //  1 XAF 500
XAF1000,    //  2 XAF 1000
XAF2500,    //  3 XAF 2500
XAF5000,    //  4 XAF 5000
XAF10000,    //  5 XAF 10000
XAF25000,    //  6 XAF 25000
XAF50000,    //  7 XAF 50000
VOUCHER,    //   VOUCHER
ENTER_NUM_OF_PIN,    //  Enter Number of PIN
VOUCHER_CAP,    //  Voucher
NUMBER,    //  Number
OK_CONFIRM,    //  Press OK to confirm
ENTER_PWD,    //  Enter Password
PLUS_OK,    //  + OK
PROCESSING,    //  Processing
SENDING,    //  Sending
RECEIVING,    //  Receiving
OPERATION_SUCCESS,    //  OPERATION SUCCESS
OK_TO_PRINT,    //  Press OK to print
CANCEL_FOR_MAIN_MENU,    //  CANCEL for MAIN MENU
OPERATION_FAILURE,    //  OPERATION FAILURE
REASON,    //   REASON
OK_TO_MENU,    //  Press OK to return to menu
NO_PROVISION_ERR_TEXT1,    //  REMOTE STOCK IS NOT
NO_PROVISION_ERR_TEXT2,    //  ENOUGH TO SATISFY
NO_PROVISION_ERR_TEXT3,    //  REQUEST
ABOVE_MAX_ERR_TEXT1,    //  NUMBER ENTERED IS
ABOVE_MAX_ERR_TEXT2,    //  ABOVE MAXIMUM
ABOVE_MAX_ERR_TEXT3,    //  ALLOWED
CONN_ERR_TEXT1,    //  CONNECTION ERROR
CONN_ERR_TEXT2,    //  DURING TRANSACTION
AN_ERR_HAPPEN,    //  AN ERROR HAPPENS
LOCAL_STOCK,    //  LOCAL STOCK
REMOTE_STOCK,    //   REMOTE STOCK
AUTH_ERROR,    //  AUTHENTICATION ERROR
SELECT_FACE_VALUE,    //  SELECT FACE VALUE
ENTER_NUM_OF_VOUCHER,    //  Enter Number of Voucher
F1_TO_ADD,    //  Press F1 to add voucher
SALES_TRANS,    //  SALES TRANSACTION
SELL_VOUCHER,    //  SELL VOUCHER
TRANS_SUCCESS,    //  TRANSACTION SUCCESS
PRESS_OK,    //  Press OK
}StringResID; 

typedef enum{
 ENGLISHLT,
}LanguageType;

#endif

